name: Show Repo

on:
  - workflow_dispatch

jobs:
  show:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v4

      # set to private at the beginning of February
      - name: 'Show Repo'
        run: gh repo edit ${{ github.repository }} --visibility public
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
  
  publish:
    needs: show

    permissions:
      pages: write
      id-token: write
    
    environment:
      name: github-pages

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build GH Pages Artifact
        uses: actions/upload-pages-artifact@v2

      - name: Publish to GH Pages
        uses: actions/deploy-pages@v2