name: Show Repo

on:
  - workflow_dispatch

jobs:
  show:
    runs-on: ubuntu-latest

    steps:
      # set to private at the beginning of February
      - name: 'Show Repo'
        run: gh repo edit ${{ github.repository }} --visibility public
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
