name: Show Repo

on:
  - workflow_dispatch

jobs:
  show:
    runs-on: ubuntu-latest

    steps:
      # set to private at the beginning of February
      - name: 'Show Repo'
        run: gh repo edit ${{ github.repository }} --visibility public
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
  
  build:
    needs: show

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true
          token: ${{ secrets.GH_TOKEN }}

      - name: Build GH Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './'

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write
      actions: read
    
    environment:
      name: github-pages

    runs-on: ubuntu-latest

    steps:
      - name: Publish to GH Pages
        uses: actions/deploy-pages@v4
